---
title: "Week 2 assignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(ggplot2)
```

## Loading and preprocessing the data

If not present, create data folder:

```{r data folder }
if(!file.exists("./data"))
    {dir.create("./data")}
```

If not present dowload zip data, if not already done unzip it:

```{r download zip}
URLfile<-"https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
if(!file.exists("./data/repdata-data-activity.zip")){
    download.file(URLfile, "./data/repdata-data-activity.zip", method = "curl")
}

if(!file.exists("./data/activity.csv")){
    unzip("./data/repdata-data-activity.zip", exdir = "./data")
}
```

Read data into R:

```{r reading}
activity <- read.csv("./data/activity.csv")

```

## What is mean total number of steps taken per day?

Plotting histogram of total number of steps per day:

```{r stepsperday, echo=FALSE}
dates<-unique(activity$date)
stepsperday<-vector()
datesrep<-vector()

for(current in dates){
    c<-sum(activity[activity$date==current,]$steps)
    
    if(!is.null(c) & !is.na(c) & !is.nan(c)){
        datesrep<- c(datesrep, rep(current,c))
        stepsperday<- c(stepsperday,c)
    }
}
mea <- as.character(mean(as.numeric(stepsperday)))
med <- as.character(median(as.numeric(stepsperday)))
qplot(datesrep) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Total average number of steps taken per day is `r mea`, the median is `r med`
